# Generated by Django 4.1.5 on 2023-01-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0002_proved_alasan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preorder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gudang.preorder')),
            ],
        ),
    ]
