# Generated by Django 4.1.5 on 2023-01-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0003_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='preorder_id',
        ),
        migrations.AddField(
            model_name='status',
            name='bahan',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='harga',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='nama_penulis',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='produk',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='proved_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gudang.proved'),
        ),
        migrations.AddField(
            model_name='status',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='suplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gudang.suplier'),
        ),
        migrations.AddField(
            model_name='status',
            name='ukuran',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='warna',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
