# Generated by Django 3.2.16 on 2023-01-15 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0004_remove_status_preorder_id_status_bahan_status_harga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='bahan',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='harga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='nama_penulis',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='produk',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='proved_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gudang.proved'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='suplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gudang.suplier'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='ukuran',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='warna',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
