# Generated by Django 4.1.5 on 2023-01-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0005_auto_20230115_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='suplier',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='suplier',
            name='nomor_wa',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preorder',
            name='suplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suplier', to='gudang.suplier'),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='datasup',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='nama_suplier',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
