# Generated by Django 4.1.5 on 2023-01-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0006_suplier_cover_suplier_nomor_wa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='cover',
            field=models.ImageField(null=True, upload_to='media/cover/'),
        ),
    ]
